name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  syntax:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci --ignore-scripts
      - run: npm run postinstall
      - run: npm test
